/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 SecondModifiedBatiment.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SecondModifiedBatiment(props) {
  const { nodes, materials } = useGLTF('/SecondModifiedBatiment.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rg08_Cube014.geometry} material={materials.Material_0} position={[-0.109, 1.861, 0.253]} />
    </group>
  )
}

useGLTF.preload('/SecondModifiedBatiment.gltf')
